config/routes.rb
Rails.application.routes.draw do
  get 'user_awards/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tops#index'
  resources :reports
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reports
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/user_award.rb
class UserAward < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      @current_user = current_user
      @user_awards = UserAward.find_by(user_id: @current_user.id)
      @user_awards&.award_1 = true
      @user_awards&.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def report_params
    params.require(:report).permit(:study_time, :study_curriculum, :study_content, :reflection).merge(user_id: current_user&.id)
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index

  end
end

app/controllers/user_awards_controller.rb
class UserAwardsController < ApplicationController
  def index
    @awards = [
      "初めての投稿",
      "2回目の投稿",
      "3回目の投稿",
      "5回目の投稿",
      "10回目の投稿",
      "15回目の投稿",
      "30回目の投稿",
      "振り返りの文字数が100文字を超える",
      "振り返りの文字数が150文字を超える",
      "10時間以上勉強する",
    ]
    @current_user = current_user

    @user_awards = UserAward.find_by(user_id: @current_user.id)

  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super

    @user_awards = UserAward.new(
      user_id: @user.id,
      award_1: false,
      award_2: false,
      award_3: false,
      award_4: false,
      award_5: false,
      award_6: false,
      award_7: false,
      award_8: false,
      award_9: false,
      award_10: false,
    )
    @user_awards.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]

  def show
    @user = User.find(params[:id])
    @posts = @user.reports
  end

  private

  # def set_user
  #   @user = User.find([:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_awards_helper.rb
module UserAwardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamDevelopment2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&amp;family=Roboto:wght@400;700&amp;display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# headerここから %>
    <header class="l-header" id="header">
      <div class="l-header__site-title">
        <div class="l-header__logo">
          <h1>
            <%= link_to root_path do %>
              <%= image_tag 'https://cdn.icon-icons.com/icons2/1144/PNG/512/homepage_80953.png', alt: 'ロゴ', class: "image-tag"%>
            <% end %>
          </h1>
        </div>
      </div>
      <div class="l-header__navigation">
        <nav class="l-gnav">
        <% if user_signed_in? %>
          <div class="l-gnav__contents--before-login">
            <ul class="l-gnav__list">
              <li class="l-gnav__button">
                <%= link_to '日報を投稿する', new_report_path, style: "text-decoration: none; color: blue;margin-right:24px;", class: 'c-button--square-yellow' %>
              </li>
              <li class="l-gnav__user-link">
                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete,data: { turbo_method: :delete }, style: "margin-right:24px;" %>
              </li>
              <li>
                <%= link_to 'マイページ', user_path(current_user), style: "margin-right:24px;" %>
              </li>
              <li>
                <%= link_to 'アワード一覧', "/user_awards/index", style: "margin-right:24px;" %>
              </li>
            </ul>
          </div>
        <% else %>
          <div class="l-gnav__contents--before-login">
            <ul class="l-gnav__list">
              <li class="l-gnav__button">
                <%= link_to '日報を投稿する', new_report_path, style: "text-decoration: none; color: blue;", class: 'c-button--square-yellow' %>
              </li>
              <li class="l-gnav__link">
                <%= link_to 'ログイン',new_user_session_path, style: "text-decoration: none; color: blue; padding-left:30px; font-weight:bold;font-size:17px;", class: "login-button" %>
              </li>
              <li class="l-gnav__button">
                <%= link_to '新規登録',new_user_registration_path, style: "text-decoration: none; color: blue;", class: 'c-button--square-yellow' %>
              </li>
            </ul>
          </div>
        <% end %>
        </nav>
      </div>
    </header>
    <%# headerここまで %>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.erb
<div class="l-main__contents">
  <div class="l-main__contents__box">
    <div class="l-article__wrapper">
      <% @reports.each do |post| %>
        <div class="l-article">
          <div class="l-article__header">
            <div class="l-article__header--left">
              <div class="l-article__category-box">
                <time><%= post.created_at.strftime('%Y.%-m.%d') %></time>
              </div>
            </div>
          </div>
          <div class="l-article__main">
            <div>
              <h1><%=post.study_curriculum%></h1>
            </div>
            <div>
              <p><%=post.study_content%></p>
            </div>
            <div>
              <p><%=post.study_time%>時間</p>
            </div>
            <div class="l-article__description">
              <%= simple_format(post.reflection) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="l-main">
  <div class="l-main__header">
    <h2 class="l-main__header__title text-green">日報を投稿する</h2>
  </div>
  <div class="l-form">
    <%= form_with model: @report, local: true, class: 'p-form__input' do |f| %>
      <div class="p-form__input-field">
        <%= f.label :"学習時間を選択する" %>
        <%= f.text_field :"study_time", autofocus: true %>
      </div>

      <div class="p-form__input-field">
        <%= f.label :"学習内容", class: 'require' %>
        <%= f.text_area :study_content, autofocus: true %>
      </div>

      <div class="p-form__input-field">
        <%= f.label :"振り返り", class: 'require' %>
        <%= f.text_area :reflection, autofocus: true %>
      </div>

      <div class="p-form__input-submit">
        <%= f.submit "投稿する", class: 'p-button c-button--submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tops/index.html.erb
<div style="text-align: center;">
    <h1 style="font-size: 100px; margin-top: 50px; margin-bottom: 30px;">簡単日報</h1>
    <p style="margin: 8px;">簡単日報はアプレンティス生のための日報投稿アプリです</p>
    <p style="margin: 8px;">楽しく日報を投稿していきましょう</p>
    <a href="#" style="text-decoration: none; color: white; margin-top: 30px; margin-bottom: 15px; display: inline-block; border-radius: 4px; background-color: #e8b615; font-size: 16px; padding: 16px 24px;">新規登録はこちら</a>
    <p>もしくは</p>
    <a href="#" style="margin-top: 15px; text-decoration: none; color: white; display: inline-block; border-radius: 4px; background-color: #e8b615; font-size: 16px; padding: 16px 24px;">ログインはこちら</a>
</div>

app/views/user_awards/index.html.erb
<div class="title">
    <div class="container">
        <h1>アワード一覧</h1>
    </div>
</div>
<div class="main-wrapper">
    <div class="container">
       <div class="one-award">
            <div class="award-title">
                <p><%= @awards[0] %></p>
            </div>
            <% if @user_awards&.award_1 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[1] %></p>
            </div>
            <% if @user_awards&.award_2 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[3] %></p>
            </div>
            <% if @user_awards&.award_4 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[4] %></p>
            </div>
            <% if @user_awards&.award_5 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[5] %></p>
            </div>
            <% if @user_awards&.award_6 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[6] %></p>
            </div>
            <% if @user_awards&.award_7 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[7] %></p>
            </div>
            <% if @user_awards&.award_8 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[8] %></p>
            </div>
            <% if @user_awards&.award_9 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
        <div class="one-award">
            <div class="award-title">
                <p><%= @awards[9] %></p>
            </div>
            <% if @user_awards&.award_10 == true %>
                <div class="award-bool">
                    <img class="yes" src="https://www.bezybox.net/sozai/wp-content/uploads/2020/05/medal-icon01_1200x630.png" alt="">
                </div>
            <% else %>
                <div class="award-bool not">
                    <img class="no" src="https://clipground.com/images/grey-circle-png-9.png" alt="">
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <img src="https://tadworks.jp/wp-content/uploads/2020/08/profile_icon.png">
  <div class="profile-content">
    <h2><%= @user.name %></h2>
    <p><%= @user.email %></p>
  </div>
</div>

<div class="my-journals">
  <div class="container">
    <div class="my-journals-title">
      <h1>過去の投稿</h1>
    </div>
    <%# each文にする %>
    <% @posts.each do |post| %>
      <div class="my-journal">
        <%# 日報の中身 %>
        <div class="journal-body">
          <p class="journal-date"><%= post.date %></p>
          <div class="content">
            <p style="margin-top: 5px;">【学習時間】</p>
            <p class="content-body"><%= post.study_time %>時間</p>
          </div>
          <div class="content">
            <p>【学習内容】</p>
            <p class="content-body"><%= post.study_content %></p>
          </div>
          <div class="content">
            <p>【振り返り】</p>
            <p class="content-body"><%= post.reflection %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>